name: Saleor Dashboard CI-CD
env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: saleor-dashboard

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    strategy: 
      matrix:
        saleor_version: ["3.0", "3.1"]
    runs-on: ubuntu-latest
    outputs:
      ecr-registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Format Repo name
        id: format-repo-name
        run: |
          # BASH string manipulation in format ${variable_name//substring/replacement}).
          # "//" replaces all the instance of the substring.
          FORMATTED_REPO_NAME="${GITHUB_REPOSITORY//\//-}"
          echo "FORMATTED_REPO_NAME: ${FORMATTED_REPO_NAME}"
          echo "::set-output name=formatted_repo_name::${FORMATTED_REPO_NAME}"

      - name: Set up Docker Buildx for cache exporting
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GENERAL_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GENERAL_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.GENERAL_AWS_DOCKER_ROLE }}
          role-duration-seconds: 1200
          role-skip-session-tagging: true
          # Github marks AWS Account ID as a secret. That blocks sharing ECR registery url from the next step.
          # For more details please visit https://github.community/t/environment-url-not-set-because-env-may-contain-secret/153708/18
          mask-aws-account-id: no

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout Saleor Dashboard version
        working-directory: saleor-dashboard
        run: |
          git checkout "${{ matrix.saleor_version }}"

      - name: Build, tag, and push to Amazon ECR
        uses: docker/build-push-action@v2
        env:
          TAG_PREFIX: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.TAG_PREFIX }}:${{ github.sha }}
            ${{ env.TAG_PREFIX }}:${{ matrix.saleor_version }}
          cache-from: type=registry,ref=${{ env.TAG_PREFIX }}:${{ matrix.saleor_version }}
          cache-to: type=inline
